# Generated by Django 4.2.3 on 2023-07-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryJtVApp', '0002_alter_sentence_id'),
        ('DictionaryJtVApp', '0002_users'),
    ]

    operations = [
    ]
