# Generated by Django 4.2.3 on 2023-07-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryJtVApp', '0003_merge_0002_alter_sentence_id_0002_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='passwordrepeat',
        ),
        migrations.AlterField(
            model_name='paragraph',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
