# Generated by Django 4.2.3 on 2023-07-25 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryJtVApp', '0006_alter_customeruser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
