# Generated by Django 4.1.5 on 2023-08-06 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DictionaryJtVApp', '0009_remove_report_description_alter_comment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='sentence',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DictionaryJtVApp.sentence'),
        ),
    ]
